In [ ]:
!pip install -U -q tabulate

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime
from tabulate import tabulate 
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [ ]:
from google.colab import drive
# NOTE: this will pop up asking for google login permission
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
def pretty_print(title, df, n):
  print(f"\n {title}")
  print(tabulate(df.head(n),headers='keys',tablefmt='psql'))

In [ ]:
path_power = '/content/drive/MyDrive/dataset/dataset_csv/dataset-powerlifting-csv/openpowerlifting-2021-12-10-b420db66.csv'
path_us_counties = '/content/drive/MyDrive/dataset/dataset_csv/dataset-covid-2/us-counties.csv'
path_us_counties_recent = '/content/drive/MyDrive/dataset/dataset_csv/dataset-covid-2/us-counties-recent.csv'
path_titanic = "/content/drive/MyDrive/dataset/dataset_csv/dataset-titanic/train.csv"

In [ ]:
! ls -ltr /content/drive/MyDrive/dataset/dataset_csv/dataset-titanic/train.csv
! ls -ltr /content/drive/MyDrive/dataset/dataset_csv/dataset-powerlifting-csv/
! ls -ltr /content/drive/MyDrive/dataset/dataset_csv/dataset-covid-2/us-counties-recent.csv | grep dataset
! ls -ltr /content/drive/MyDrive/dataset/dataset_csv/dataset-covid-2/us-counties.csv | grep dataset
# /content/drive/MyDrive/

-rw------- 1 root root 61194 Jan  3 19:50 /content/drive/MyDrive/dataset/dataset_csv/dataset-titanic/train.csv
total 490785
-rw------- 1 root root 502549264 Dec 10 06:09 openpowerlifting-2021-12-10-b420db66.csv
-rw------- 1 root root     12778 Dec 10 06:09 README.txt
-rw------- 1 root root      1142 Dec 10 06:09 LICENSE.txt
-rw------- 1 root root 4174593 Jan 11 01:10 /content/drive/MyDrive/dataset/dataset_csv/dataset-covid-2/us-counties-recent.csv
-rw------- 1 root root 87436511 Jan 11 01:10 /content/drive/MyDrive/dataset/dataset_csv/dataset-covid-2/us-counties.csv

In [ ]:
# read titanic 
df_in_titanic = pd.read_csv(path_titanic)
# read powerlifting
df_in_power = pd.read_csv(path_power)

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (33,35,38) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [ ]:
# LABEL ENCODER EXAMPLE WITH POWERLIFTING DATA SET

labelencoder = LabelEncoder()
df_usa_men_val['encoded_equipment'] = labelencoder.fit_transform(df_usa_men_val['Equipment'])

pretty_print("title ", df_usa_men_val, 2)

lst_sel_cols = ["Equipment", "encoded_equipment"]

pretty_print("Selective columns print Equipment and encoded_equipment:", df_usa_men_val[lst_sel_cols], 10)

 title
+------+----------------+-------+---------+-------------+-------+------------+------------------+------------+----------------+-----------------+------------+------------+------------+------------+----------------+------------+------------+------------+------------+----------------+---------------+---------------+---------------+---------------+-------------------+-----------+---------+--------+---------+----------------+------------+----------+-----------+---------+--------------+--------------------+------------+---------------+-------------+------------+-------------------------------------+--------------+---------------+---------------------+
|      | Name           | Sex   | Event   | Equipment   |   Age | AgeClass   | BirthYearClass   | Division   |   BodyweightKg |   WeightClassKg |   Squat1Kg |   Squat2Kg |   Squat3Kg |   Squat4Kg |   Best3SquatKg |   Bench1Kg |   Bench2Kg |   Bench3Kg |   Bench4Kg |   Best3BenchKg |   Deadlift1Kg |   Deadlift2Kg |   Deadlift3Kg |   Deadlift4Kg |   Best3DeadliftKg |   TotalKg | Place   |   Dots |   Wilks |   Glossbrenner |   Goodlift |   Tested | Country   |   State | Federation   | ParentFederation   | Date       | MeetCountry   |   MeetState | MeetTown   | MeetName                            |   bucket_age |   encoded_age |   encoded_equipment |
|------+----------------+-------+---------+-------------+-------+------------+------------------+------------+----------------+-----------------+------------+------------+------------+------------+----------------+------------+------------+------------+------------+----------------+---------------+---------------+---------------+---------------+-------------------+-----------+---------+--------+---------+----------------+------------+----------+-----------+---------+--------------+--------------------+------------+---------------+-------------+------------+-------------------------------------+--------------+---------------+---------------------|
|  698 | Daniel Ramires | M     | SBD     | Wraps       |  27   | 24-34      | 24-39            | MO         |           67.5 |            67.5 |        nan |        nan |        nan |        nan |            nan |        nan |        nan |        nan |        nan |            nan |           nan |           nan |           nan |           nan |               nan |       500 | 1       | 385.37 |  385.51 |         374.21 |      77.02 |      nan | USA       |     nan | GPC          | GPC                | 2018-11-25 | Brazil        |         nan | Itanhaém   | South American Championships        |            1 |            33 |                   5 |
| 2955 | João Gonçalves | M     | SBD     | Raw         |  24.5 | 24-34      | 24-39            | Open       |           88.6 |            90   |        nan |        nan |        nan |        nan |            nan |        nan |        nan |        nan |        nan |            nan |           nan |           nan |           nan |           nan |               nan |       nan | DQ      | nan    |  nan    |         nan    |     nan    |      nan | USA       |     nan | WPC-Portugal | WPC                | 2018-05-05 | Portugal      |         nan | nan        | Campeonato Nacional de Powerlifting |            1 |            28 |                   1 |
+------+----------------+-------+---------+-------------+-------+------------+------------------+------------+----------------+-----------------+------------+------------+------------+------------+----------------+------------+------------+------------+------------+----------------+---------------+---------------+---------------+---------------+-------------------+-----------+---------+--------+---------+----------------+------------+----------+-----------+---------+--------------+--------------------+------------+---------------+-------------+------------+-------------------------------------+--------------+---------------+---------------------+

 Selective columns print:
+------+-------------+---------------------+
|      | Equipment   |   encoded_equipment |
|------+-------------+---------------------|
|  698 | Wraps       |                   5 |
| 2955 | Raw         |                   1 |
| 5478 | Multi-ply   |                   0 |
| 5569 | Wraps       |                   5 |
| 5571 | Wraps       |                   5 |
| 5579 | Wraps       |                   5 |
| 5586 | Multi-ply   |                   0 |
| 5675 | Multi-ply   |                   0 |
| 5698 | Raw         |                   1 |
| 5922 | Wraps       |                   5 |
+------+-------------+---------------------+

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [ ]:
# ONE HOT ENCODING EXAMPLE WITH POWERLIFTING DATA SET ("SEX")

# usa men only
df_usa = df_in_power[(df_in_power["Country"] == "USA")]
# print distinct gender
print(f"distinct gender -> {df_in_power['Sex'].unique()}")
# drop na for "Sex"
# df_usa["Sex"].dropna(inplace=True)
df_usa.dropna(subset=['Sex'], how='all', inplace=True)
# age with valid numbers only (above 10)
df_usa_val = df_usa[df_usa["Age"] > 10]
# one hot encoder
enc = OneHotEncoder(handle_unknown='ignore')
# pass "Sex" column for fit into transformation
enc_df = pd.DataFrame(enc.fit_transform(df_usa_val[['Sex']]).toarray())
# merge both df
df_merge = df_usa_val.join(enc_df)
# list of new merged df (three new columns since three distinct value for column "Sex" 
# as "M", "F", "Mx")
lst_columns = list(df_usa_val) + ["M", "F", "O"]
# rename the new columns
df_merge.columns = lst_columns
# three new columns (corresponding to "M", "F", "Mx" in column "Sex")
lst_sel_cols = ["M", "F", "O"]
lst_sel_cols_2 = ["Sex"] + lst_sel_cols

# "M" only
filter_1 = df_merge["M"] == 1
pretty_print("Sex: 'M' only", df_merge[filter_1][lst_sel_cols_2], 10)
# "F" only
filter_2 = df_merge["F"] == 1
pretty_print("Sex: 'F' only", df_merge[filter_2][lst_sel_cols_2], 10)
# "Mx" only
filter_3 = df_merge["Sex"] == "Mx"
pretty_print("Sex: 'O' only", df_merge[filter_3][lst_sel_cols_2], 10)

distinct gender -> ['F' 'M' 'Mx']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

 Sex: 'M' only
+------+-------+-----+-----+-----+
|      | Sex   |   M |   F |   O |
|------+-------+-----+-----+-----|
| 5569 | M     |   1 |   0 |   0 |
| 5571 | M     |   1 |   0 |   0 |
| 5739 | F     |   1 |   0 |   0 |
| 5890 | F     |   1 |   0 |   0 |
| 6100 | M     |   1 |   0 |   0 |
| 6133 | M     |   1 |   0 |   0 |
| 6138 | M     |   1 |   0 |   0 |
| 6142 | M     |   1 |   0 |   0 |
| 6415 | F     |   1 |   0 |   0 |
| 6507 | M     |   1 |   0 |   0 |
+------+-------+-----+-----+-----+

 Sex: 'F' only
+------+-------+-----+-----+-----+
|      | Sex   |   M |   F |   O |
|------+-------+-----+-----+-----|
|  698 | M     |   0 |   1 |   0 |
| 2955 | M     |   0 |   1 |   0 |
| 5478 | M     |   0 |   1 |   0 |
| 5542 | F     |   0 |   1 |   0 |
| 5556 | F     |   0 |   1 |   0 |
| 5579 | M     |   0 |   1 |   0 |
| 5586 | M     |   0 |   1 |   0 |
| 5675 | M     |   0 |   1 |   0 |
| 5698 | M     |   0 |   1 |   0 |
| 5922 | M     |   0 |   1 |   0 |
+------+-------+-----+-----+-----+

 Sex: 'O' only
+---------+-------+-----+-----+-----+
|         | Sex   |   M |   F |   O |
|---------+-------+-----+-----+-----|
|  300158 | Mx    |   1 |   0 |   0 |
|  329710 | Mx    |   1 |   0 |   0 |
|  338407 | Mx    |   0 |   1 |   0 |
|  343566 | Mx    |   1 |   0 |   0 |
|  393099 | Mx    |   0 |   1 |   0 |
|  402722 | Mx    |   0 |   1 |   0 |
| 1836984 | Mx    | nan | nan | nan |
| 1897378 | Mx    | nan | nan | nan |
| 1902380 | Mx    | nan | nan | nan |
| 1908731 | Mx    | nan | nan | nan |
+---------+-------+-----+-----+-----+

In [ ]:
# LABEL ENCODER EXAMPLE WITH TITANIC DATA SET

# actual read from the csv file
pretty_print("titanic:", df_in_titanic, 2)

# take only categorical data with select_dtypes
df_in_titanic_cat = df_in_titanic.select_dtypes(include=[object])
pretty_print("titanic (cat only):", df_in_titanic_cat, 2)
# label encoder
le = LabelEncoder()
# fit transform
df_tit_label = df_in_titanic_cat.apply(le.fit_transform)
pretty_print("label encoded for categorical columns only:", df_tit_label, 5)

 titanic:
+----+---------------+------------+----------+-----------------------------------------------------+--------+-------+---------+---------+-----------+---------+---------+------------+
|    |   PassengerId |   Survived |   Pclass | Name                                                | Sex    |   Age |   SibSp |   Parch | Ticket    |    Fare | Cabin   | Embarked   |
|----+---------------+------------+----------+-----------------------------------------------------+--------+-------+---------+---------+-----------+---------+---------+------------|
|  0 |             1 |          0 |        3 | Braund, Mr. Owen Harris                             | male   |    22 |       1 |       0 | A/5 21171 |  7.25   | nan     | S          |
|  1 |             2 |          1 |        1 | Cumings, Mrs. John Bradley (Florence Briggs Thayer) | female |    38 |       1 |       0 | PC 17599  | 71.2833 | C85     | C          |
+----+---------------+------------+----------+-----------------------------------------------------+--------+-------+---------+---------+-----------+---------+---------+------------+

 titanic (cat only):
+----+-----------------------------------------------------+--------+-----------+---------+------------+
|    | Name                                                | Sex    | Ticket    | Cabin   | Embarked   |
|----+-----------------------------------------------------+--------+-----------+---------+------------|
|  0 | Braund, Mr. Owen Harris                             | male   | A/5 21171 | nan     | S          |
|  1 | Cumings, Mrs. John Bradley (Florence Briggs Thayer) | female | PC 17599  | C85     | C          |
+----+-----------------------------------------------------+--------+-----------+---------+------------+

 label encoded for categorical columns only:
+----+--------+-------+----------+---------+------------+
|    |   Name |   Sex |   Ticket |   Cabin |   Embarked |
|----+--------+-------+----------+---------+------------|
|  0 |    108 |     1 |      523 |     147 |          2 |
|  1 |    190 |     0 |      596 |      81 |          0 |
|  2 |    353 |     0 |      669 |     147 |          2 |
|  3 |    272 |     0 |       49 |      55 |          2 |
|  4 |     15 |     1 |      472 |     147 |          2 |
+----+--------+-------+----------+---------+------------+

Reference:

https://www.ritchieng.com/machinelearning-one-hot-encoding/

https://towardsdatascience.com/building-a-one-hot-encoding-layer-with-tensorflow-f907d686bf39

https://www.geeksforgeeks.org/ml-one-hot-encoding-of-datasets-in-python/